// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MotoRodeo.DAL.Context;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MotoRodeo.DAL.Migrations
{
    [DbContext(typeof(MotoRodeoContext))]
    partial class MotoRodeoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MotoRodeo.DAL.Entities.DBAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Confirmed")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(127)
                        .HasColumnType("character varying(127)");

                    b.Property<long>("Identifier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Identifier"));

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(127)
                        .HasColumnType("character varying(127)");

                    b.Property<long>("LastUpdateTick")
                        .HasColumnType("bigint");

                    b.Property<string>("Login")
                        .HasMaxLength(127)
                        .HasColumnType("character varying(127)");

                    b.Property<string>("Vehicle")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("FirstName", "LastName", "Login")
                        .IsUnique();

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("MotoRodeo.DAL.Entities.DBAccountLogin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountLoginType")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<long>("LastUpdateTick")
                        .HasColumnType("bigint");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(127)
                        .HasColumnType("character varying(127)");

                    b.Property<string>("Password")
                        .HasMaxLength(2047)
                        .HasColumnType("character varying(2047)");

                    b.HasKey("Id");

                    b.HasIndex("Login", "AccountLoginType")
                        .IsUnique();

                    b.ToTable("AccountLogins");
                });

            modelBuilder.Entity("MotoRodeo.DAL.Entities.DBAccountRight", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("LastUpdateTick")
                        .HasColumnType("bigint");

                    b.Property<Guid>("Right")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AccountId", "Right")
                        .IsUnique();

                    b.ToTable("AccountRights");
                });

            modelBuilder.Entity("MotoRodeo.DAL.Entities.DBEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("EventDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("GroupCount")
                        .HasColumnType("integer");

                    b.Property<long>("LastUpdateTick")
                        .HasColumnType("bigint");

                    b.Property<string>("Place")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTimeOffset>("RegistrationClosesAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Status")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("MotoRodeo.DAL.Entities.DBEventGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<long>("LastUpdateTick")
                        .HasColumnType("bigint");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EventId", "Number")
                        .IsUnique();

                    b.ToTable("EventGroups");
                });

            modelBuilder.Entity("MotoRodeo.DAL.Entities.DBEventJudge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<long>("LastUpdateTick")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("EventId", "AccountId")
                        .IsUnique();

                    b.ToTable("EventJudges");
                });

            modelBuilder.Entity("MotoRodeo.DAL.Entities.DBEventParticipant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<long>("LastUpdateTick")
                        .HasColumnType("bigint");

                    b.Property<Guid>("Status")
                        .HasColumnType("uuid");

                    b.Property<bool>("UsesOwnEquipment")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("EventId", "AccountId")
                        .IsUnique();

                    b.ToTable("EventParticipants");
                });

            modelBuilder.Entity("MotoRodeo.DAL.Entities.DBGroupMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<long>("LastUpdateTick")
                        .HasColumnType("bigint");

                    b.Property<int>("StartNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GroupId", "AccountId")
                        .IsUnique();

                    b.HasIndex("GroupId", "StartNumber")
                        .IsUnique();

                    b.ToTable("GroupMembers");
                });

            modelBuilder.Entity("MotoRodeo.DAL.Entities.DBHeat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChaserAccountId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<long>("LastUpdateTick")
                        .HasColumnType("bigint");

                    b.Property<Guid>("LeaderAccountId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MatchupId")
                        .HasColumnType("uuid");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GroupId", "Sequence")
                        .IsUnique();

                    b.ToTable("Heats");
                });

            modelBuilder.Entity("MotoRodeo.DAL.Entities.DBPasswordResetRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean");

                    b.Property<long>("LastUpdateTick")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("PasswordResetRequests");
                });

            modelBuilder.Entity("MotoRodeo.DAL.Entities.DBAccountLogin", b =>
                {
                    b.HasOne("MotoRodeo.DAL.Entities.DBAccount", "Account")
                        .WithMany("AccountLogins")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("MotoRodeo.DAL.Entities.DBAccountRight", b =>
                {
                    b.HasOne("MotoRodeo.DAL.Entities.DBAccount", "Account")
                        .WithMany("AccountRights")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("MotoRodeo.DAL.Entities.DBEventGroup", b =>
                {
                    b.HasOne("MotoRodeo.DAL.Entities.DBEvent", "Event")
                        .WithMany("Groups")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("MotoRodeo.DAL.Entities.DBEventJudge", b =>
                {
                    b.HasOne("MotoRodeo.DAL.Entities.DBAccount", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MotoRodeo.DAL.Entities.DBEvent", "Event")
                        .WithMany("Judges")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Event");
                });

            modelBuilder.Entity("MotoRodeo.DAL.Entities.DBEventParticipant", b =>
                {
                    b.HasOne("MotoRodeo.DAL.Entities.DBAccount", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MotoRodeo.DAL.Entities.DBEvent", "Event")
                        .WithMany("Participants")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Event");
                });

            modelBuilder.Entity("MotoRodeo.DAL.Entities.DBGroupMember", b =>
                {
                    b.HasOne("MotoRodeo.DAL.Entities.DBAccount", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MotoRodeo.DAL.Entities.DBEventGroup", "Group")
                        .WithMany("Members")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("MotoRodeo.DAL.Entities.DBHeat", b =>
                {
                    b.HasOne("MotoRodeo.DAL.Entities.DBAccount", "Chaser")
                        .WithMany()
                        .HasForeignKey("ChaserAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MotoRodeo.DAL.Entities.DBEventGroup", "Group")
                        .WithMany("Heats")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MotoRodeo.DAL.Entities.DBAccount", "Leader")
                        .WithMany()
                        .HasForeignKey("LeaderAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Chaser");

                    b.Navigation("Group");

                    b.Navigation("Leader");
                });

            modelBuilder.Entity("MotoRodeo.DAL.Entities.DBPasswordResetRequest", b =>
                {
                    b.HasOne("MotoRodeo.DAL.Entities.DBAccount", "Account")
                        .WithMany("PasswordResetRequests")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("MotoRodeo.DAL.Entities.DBAccount", b =>
                {
                    b.Navigation("AccountLogins");

                    b.Navigation("AccountRights");

                    b.Navigation("PasswordResetRequests");
                });

            modelBuilder.Entity("MotoRodeo.DAL.Entities.DBEvent", b =>
                {
                    b.Navigation("Groups");

                    b.Navigation("Judges");

                    b.Navigation("Participants");
                });

            modelBuilder.Entity("MotoRodeo.DAL.Entities.DBEventGroup", b =>
                {
                    b.Navigation("Heats");

                    b.Navigation("Members");
                });
#pragma warning restore 612, 618
        }
    }
}